[[unarmed]]
= Unarmed
The art of combat without weapons, emphasizing physical strength and technique. The primary skill is <<strength, Strength>>. Base damage for unarmed attacks is 1 for the main attack and 0 for off-hand attacks.

== Rank I
- [[disarm]]Disarm: Instead of making an attack or off-hand attack, you can attempt to disarm a target. On success, the target drops their weapon.
- <<hold, Hold>>: Attempt to hold a target and attack it as a single action by spending 1 EP. On success, the target is considered held.

== Rank II
- Disarm: On a successful disarm attempt, you deal full damage.
- Damage Increase: Unarmed attack damage increases by 1 for both the main attack and off-hand attacks.
- Hold: You no longer need to spend 1 EP to use this skill.
- <<grab, Grab>>: Attempt to grab a target and attack it as a single action by spending 1 EP. On success, the target is considered grabbed. You need *hold* perk to use this skill. If you try to grab the held target, the <<enemies, difficulty>> of this check is halved.
