= Vision and Position

[[cover]]
== Cover

Creatures can benefit from cover, which comes in the following types:

[[partial-cover]] 
- **Partial Cover**: The target is partially obscured by an obstacle, such as a rock or tree. This reduces the attack roll dice pool against the creature by **one** die.
[[heavy-cover]] 
- **Heavy Cover**: The target is almost completely obscured by an obstacle, such as a wall or building. This reduces the attack roll dice pool against the creature by **two** dice.
[[full-cover]] 
- **Full Cover**: The target is completely obscured by an obstacle and is considered *hidden* but *<<undetected, detected>>*.

== Seen, Hidden, and Undetected Characters

Seeing a target is required for certain actions and attacks. [[hidden]]*Hidden* characters cannot be targeted by single-target attacks or skills at range. However, targets situated in melee range can still be attacked based on hearing or other senses, though such attacks incur a penalty of **one** die. Hidden characters can still be affected by area-of-effect abilities. Creatures remain hidden until they attack or are discovered.

*[[undetected]] Undetected characters* — characters the attacker is unaware of — cannot be targeted by single-target or area-of-effect actions.

[[surprised]]
== Surprised Targets

Surprise attacks occur when an undetected character attacks a target. The attacker gains a short round during which they can perform one action. Targeted creatures cannot react to the attack. After the attack, undetected characters become seen.

[[pose]]
== Crouching, Laying, Getting Up and High Ground

A character's pose plays an important role, giving bonuses or penalties to their attacks and defenses. These effects depend on the poses of both the attacker and the defender, as well as their positions on the battlefield. For example, crouching behind a low wall might provide full cover, which would not work for a standing character. On the other hand, targeting a prone character from higher ground can be easier than targeting a standing one, though this advantage is not the case for flat terrain.

Weapons also influence these bonuses and penalties. For instance, attacking a prone character in melee is generally easier than attacking a standing character, but attacking a prone character with a ranged weapon is usually harder. The attack rolls of crouching or prone characters using ranged weapons depend on the weapon type: easily reloaded firearms are often easier to use while crouching or lying down, whereas bows and slings are more difficult to handle in such positions.

Changing your pose is a <<short-action,short action>>, except getting up which is a <<full-action,full action>>.
