= Zones

The battlefield is divided into distinct zones. A character's position within a zone is significant; zones may contain obstacles such as rocks, bushes, or other terrain features. Positioning behind these obstacles can provide <<cover, cover>> from enemies, while positioning in front of them leaves you vulnerable.

[[move]]
== Movement

Movement within the same zone is considered a <<short-action,short action>>. Stepping into an adjacent zone from the border of your current zone is also a short action. However, moving to a new zone from any other point within the current zone requires a full action.

[[dash]]
== Dash

*Dash* is a <<action-variety,variety>> of the *move* action. It allows a character to move 2 zones in one action but requires 1 EP. 

[[hard-to-move]]
== Zone Effects

Certain zones may impose movement restrictions, such as slippery or uneven terrain. These zones can increase the cost of movement. For example:

- Characters might need to spend two actions to move a single zone.
- A full action may be required instead of a short action.
- An additional energy point (EP) might need to be expended alongside the action.
