[[heavy-armor]]
= Heavy Armor
The skill of wearing and maintaining heavy protective gear. The primary attribute for this skill is <<strength, Strength>>.

When you equip a heavy armor, you gain the following effects:
- [[heavy-armored]]Heavy Armored: Your difficulty for incoming attacks increases by *2*. However, it decreases your <<spd, Speed>>, <<agility, Agility>>, and <<stealth, Stealth>>, as well as any test to cast a spell, by *2*.
- [[heavy-armor-block]]Armor Block: Reduces damage received from attacks by *2* at the cost of 1 EP and 1 <<item-use-token, item use token>>. Does not require an action.

== Rank I
- Heavy Armored: Reduces the penalties for your Speed, Agility and Stealth from wearing heavy armor by *1*.
- Heavy Armored: Reduces the penalties for casting spells from wearing heavy armor by *1*.

== Rank II
- Armor Block: Increases the damage reduction to *3*.
- Heavy Armored: Reduces the penalties for your Speed, Agility and Stealth from wearing heavy armor by another *1*.
- Heavy Armored: Reduces the penalties for casting spells from wearing heavy armor by another *1*.
- Heavy Armored: Increases your difficulty for incoming attacks by another *1*.
- Heavy Armor Feels Like Pajamas: Removes penalties for sleeping in heavy armor and reduces the time required to equip heavy armor by half.
