= Light Armor
The skill of wearing and maintaining lightweight protective gear. The primary skill is <<agility, Agility>>.

When you wearing a light armor, you gain the following effects:
- [[lightly-armored]]Lightly Armored: Your difficulty for incoming attacks increases by *1*. However, it decreases your <<spd, Speed>>, <<agility, Agility>>, and <<stealth, Stealth>>, as well as any test to cast a spell, by *1*.

== Rank I
- [[light-armor-block]]Armor Block: Reduces damage received from attacks by *1* at the cost of 1 EP and 1 <<item-use-token, item use token>>. Does not require an action.
- Lightly Armored: Completely removes penalties for Speed, Agility and Stealth from wearing light armor.
- Lightly Armored: Completely removes penalties for casting spells from wearing light armor.
- Light Armor Feels Like a Second Skin: Removes penalties for sleeping in light armor and reduces the time required to equip light armor by half.

== Rank II
- Armor Block: Increases the damage reduction to *2*.
- Lightly Armored: Your difficulty for incoming attacks is increased by another *1*.
