= Lore: Religion
Knowledge of religious practices, beliefs, and deities.

The Religion skill is used to identify the nature of a deity, their followers, and their practices. It can also be used to identify the nature of a curse or blessing and determine the effects of a curse or blessing.

The Religion test is performed in the following action:

- [[follow-superstition]]Follow a superstition: On success, remove a curse from yourself.

== Rank I
- [bless]Bless: As an action, <<blessed, bless 2>> a target on a success. The effect lasts until the end of the round.
- [curse]Curse: As an action, curse a target on a success, making it <<cursed, cursed 5>>, the effect last until the end of the round.

== Rank II
- Bless: As an action, bless a target on a success, making it **blessed 6**.
- Bless: Bless a target without requiring a roll.
- Bless: You can choose up to *two* creatures to bless at once. The creatures must be in the same zone.
- Curse: As an action, curse a target on a success, making it <<cursed 1>>.
- Curse: You can choose up to *two* creatures to curse at once. The creatures must be in the same zone.
