= Lore: Religion
Knowledge of religious practices, beliefs, and deities.

The Religion skill is used to identify the nature of a deity, their followers, and their practices.
It can also be used to identify the nature of a curse or blessing and determine the effects of a curse or blessing.

The Religion test is performed in the following action:

- [[follow-superstition]]Follow a superstition: On success, remove a curse from yourself.
- Resist a curse: A test performed when someone tries to curse you.
On success, you resist the effects of the curse.
Does not require an action.

== Rank I
- [[bless]][[curse]]Bless/Curse: As an action, bless a target on a success, making it <<blessed, blessed 2>>, or curse a target on a success, making it <<cursed, cursed 5>>. 
The effect lasts until the end of the round, and the target must be in the same zone as you.

- <<counter-influence>>. You perform a Religion test instead of Serenity to resist the effects of a curse or blessing.
- <<distant-influence>>.
- <<effect-on-mass>>.
- <<reliable-skill>>: Affects only a Bless.

== Rank II
- Bless/Curse: As an action, bless a target on a success, making it <<blessed, blessed 6>>, or curse a target on a success, making it <<cursed, cursed 1>>.
