[[first-aid]]
= First Aid
Basic medical knowledge for treating wounds and injuries. Can be used in combat. Primary stat is <<obs, Observation>>.

These actions can be performed in combat and requires a successful skill check. The target must be adjusted to the character performing the action.

- [[quick-patch]]Quick Patch: Restore 1 EP on success. Requires 1 EP.
- [[stabilize-condition]]Stabilize Condition: On a success reduce the severity of a medical condition (e.g., poisoned) by one level.
- Stabilize Condition: On a success reduce the duration of a medical condition (e.g., poisoned) by one round.

== Rank I
- Quick Patch: Restore 1 EP without a roll.
- Quick Patch: Restore 2 EP on success.
- Stabilize Condition: Further reduce the severity of a condition (e.g., poisoned) by one level or reduce its duration by 1 round.
- Stabilize Condition: Reduce the severity or duration of two conditions simultaneously.

== Rank II
- Quick Patch: On a success, additionally restore 1 HP.
- Stabilize Condition: Successfully stabilizing a condition makes the target immune to reapplying this condition for 1 round. Additionally, you can make a target immune to any applied condition for 1 round.
- Quick Patch: When you apply a first aid action to an unconscious target, it can act immediately.

// treat two targets
