[[insult]]
= Insult
The art of delivering cutting remarks to provoke others. The primary stat is <<chr, Charisma>>. This skill allows you to perform a provoke action.

[[provoke]]Provoke: Choose *one* creature in the same zone as you. On success, this creature is <<provoked, provoked>>, loses its current action, and instead attempts to harm you.

== Rank I
- Provoke: A provoked creature cannot move away from you during this round.
- Prolonged Provoke: The provoked target suffers a -1 die penalty on its next action if it does not harm you. You must spend 1 EP for each creature you target with this perk before the roll.
- Taunting Resilience: You can choose to spend 1 EP to take 1 less damage from the provoked creature. You can't use this ability more than once against the same attack.
- Final Word: If you reduce a provoked creature to 0 HP, one enemy of the same or lower <<enemies,difficulty>> in the same zone becomes frightened.
- <<effect-on-mass,Effect on Mass>>.
- <<distant-influence,Distant Influence>>.
// - Distraction: Successfully provoking a creature grants one ally +1 die bonus on their next action against that target. Choose an ally in the same zone as target.
// - Force a Mistake: If the provoked creature misses an attack against you, it incurs a -1 penalty to <<enemies,difficulty>> on actions against it during this stage.
// - Spiteful Style: Increase the difficulty of any mental actions from the provoked creature against you by one.
// - Ego Bruise: If a provoked creature fails to harm you until the end of the next round, it loses 1 EP out of frustration.
// - Taunting Pursuit: After provoking, you may move 1 zone closer to the provoked creature.

== Rank II
- Prolonged Provoke: A provoked creature loses its entire round instead of just one action. It retains its normal number of full and short actions but cannot do anything except attempt to harm you.
- Prolonged Provoke: If the provoked creature uses its next action without harming you, you gain one extra die when performing a test against it during this action.
- Scathing Remark: If you beat the target difficulty by 6 or more, the provoked creature loses 1 EP.
- Taunting Resilience: You receive 1 less damage from the provoked creature.
- Final Word: You can attempt to affect a creature with a higher difficulty. This requires a successful <<intimidation, Intimidation>> test against the target's <<enemies,difficulty>>. If you succeed, the target becomes frightened.
- <<counter-influence,Counter Influence>>.
// - Spiteful Style: Gain +1 EP when a creature fails a provoke or other mental action test against you.
// - Force a Mistake: Increase the penalty to -2.
