[[intimidation]]
= Intimidation
The ability to influence others through fear or threats. The primary attribute for this skill is <<strength, Strength>>.

- [[intimidate]]Intimidate: Choose *one* creature. On a success, the creature becomes <<frightened, frightened>> by you.

== Rank I
- Intimidate: You can choose up to *two* creatures, provided they are in the same zone.
- Intimidate: You can intimidate creatures in adjacent zone.
- [[terrify]]Terrify: A frightened creature cannot move during this round. 
- Terrify: A frightened creature drops its weapon.
- [[counter-intimidation]]Counter Intimidation: You experience in intimidation makes in easier to resist it. You receive +1 bonus to test <<serenity, Serenity>> against intimidation.
- [[focused-intimidation]]Focused Intimidation: You can spend 1 EP to intimidate a creature with <<enemies, difficulty>> of 7 or less without rolling.

== Rank II
- Intimidate: You can attempt to intimidate all opponents in one zone.
- Terrify: An frightened creature loses its current action, drops the weapons and instead flees from you.
- Counter Intimidation: You can attempt to intimidate a creature that is trying to intimidate you. If you succeed on the Serenity check and exceed the difficulty by 6 or more, the creature becomes frightened of you instead of you being frightened of it.
- [[counter-fear-aura]] Counter Fear Aura: Your allies in the same zone as you gain a +1 bonus to their Serenity tests to resist fear effects caused by enemies.
- Focused Intimidation: You can spend 1 EP to intimidate a creature with <<enemies, difficulty>> of 10 or less without rolling.
- Show of Force: Successfully intimidating a creature gives +1 die to your next Strength-based test this round against the target.
