[[throwing]]
= Throwing
Proficiency in accurately hurling objects or weapons. Primary skill is <<str, Strength>>.

== Rank I
- Throw: Spend 1 EP to make a roll with a result of **7**. This cannot be used if your check pool has no dice.
- [[throw-aim]]Throw Aim: The <<aim,Aim>> action no longer requires a test.
- Throw: When making a weapon attack, you can target a <<hidden, *hidden*>> but <<undetected, *detected*>> creature with your throw, as long as you are in the same zone as the target. This attack incurs a penalty of *1* die.

== Rank II
- Throw Aim: Take an action to aim, negating the cover penalty of the attack completely.
- Throw Back: When targeted by a thrown attack, you can attempt to catch the object and throw it back at the attacker. This is a <<short-action, short action>> requiring a successful throwing check. On success, you may either throw the object back at the attacker as part of this action or keep it for later use. If you choose to throw it back, the same test result is used for the attack. Alternatively, you can spend 1 EP to automatically succeed on the test and throw the object back at the attacker using the result of their test, provided it does not exceed **10**.
